#%RAML 1.0
---

title: Customs Inventory Linking Exports
version: 2.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/
mediaType: application/xml

documentation:
 - title: Overview
   content: !include docs/overview.md
 - title: Versioning
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md
 - title: Errors
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/errors.md
 - title: XML Schemas
   content: !include docs/schema.md

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

/customs/inventory-linking/exports:
  /:
    post:
      displayName: Inventory Exports Request
      description: Submit an Inventory Exports Request
      headers:
        Accept:
          description: Specifies the version of the API that you want to call. See [versioning](/api-documentation/docs/reference-guide#versioning).
          type: string
          required: true
          example: application/vnd.hmrc.2.0+xml
        Content-Type:
          description: Specifies the format of the request body, which must be XML.
          type: string
          required: true
          example: application/xml; charset=UTF-8
        X-Badge-Identifier:
            description: |
              Represents the end-user who is interacting with the subscribed application.

              Must be 6 to 12 characters, consisting of any combination of numeric digits and/or upper-case letters.
            type: string
            required: false
            example: ABC123
        X-Submitter-Identifier:
            description: |
              The EORI associated with the originating owner of the declaration.

              Must have a maximum length of 17 characters, consisting of any combination of numeric digits and/or letters.
            type: string
            required: false
            example: ABC123

      (annotations.scope): "write:customs-inventory-linking-exports"
      securedBy: [ sec.oauth_2_0: { scopes: [ "write:customs-inventory-linking-exports" ] } ]
      body:
        application/xml-1:
          type: !include schemas/customs/wrapper.xsd
          example: !include examples/example_messages/Trade%20Test%2012.3%20Sample%20Messages/TT_EX01a/Example%20Movement%20Messages/CST.xml
        application/xml-2:
          type: !include schemas/customs/wrapper.xsd
          example: !include examples/example_messages/Trade%20Test%2012.3%20Sample%20Messages/TT_EX01a/Example%20Movement%20Messages/EAL.xml
        application/xml-3:
          type: !include schemas/customs/wrapper.xsd
          example: !include examples/queryRequest.xml

      responses:
        202:
        400:
          body:
            application/xml:
              description: Invalid XML Payload
              type: !include schemas/customs/error.xsd
              example: |
                  <?xml version="1.0" encoding="UTF-8"?>
                  <errorResponse>
                      <code>BAD_REQUEST</code>
                      <message>Payload is not valid according to schema</message>
                      <errors>
                          <error>
                              <code>xml_validation_error</code>
                              <message>Error at line 13, column 13: no declaration found for element 'unknown'</message>
                          </error>
                      </errors>
                  </errorResponse>
        406:
          body:
            application/xml:
              description: Invalid Accept header
              type: !include schemas/customs/error.xsd
              example: |
                  <?xml version="1.0" encoding="UTF-8"?>
                  <errorResponse>
                    <code>ACCEPT_HEADER_INVALID</code>
                    <message>The accept header is missing or invalid</message>
                  </errorResponse>
        415:
          body:
            application/xml:
              description: Invalid Content-type header
              type: !include schemas/customs/error.xsd
              example: |
                  <?xml version="1.0" encoding="UTF-8"?>
                  <errorResponse>
                    <code>UNSUPPORTED_MEDIA_TYPE</code>
                    <message>The content type header is missing or invalid</message>
                  </errorResponse>
        500:
          body:
            application/xml:
              description: Internal server error
              type: !include schemas/customs/error.xsd
              example: |
                  <?xml version="1.0" encoding="UTF-8"?>
                  <errorResponse>
                      <code>INTERNAL_SERVER_ERROR</code>
                      <message>Internal server error</message>
                  </errorResponse>
